apiVersion: v1
kind: Service
metadata:
  name: nrf
  labels:
    epc-mode: nrf
spec:
  selector:
    epc-mode: nrf
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nrf-deployment
  labels:
    epc-mode: nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: nrf
  template:
    metadata:
      annotations:
         k8s.v1.cni.cncf.io/networks: '[
                 { "name": "{{ .Release.Name }}-sbi-nad",
                    "interface": "sbi",
                   "ips": [ {{- cat .Values.sbiAddresses.nrf "/" .Values.sbiAddresses.NetworkMask | nospace | quote }} ] }                   
         ]'    
#      annotations:
#        "helm.sh/hook": pre-install    
      labels:
        epc-mode: nrf
    spec:  
      containers:
        - name: nrf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
          - ip route add {{ .Values.roamingSBInetwork }} via {{ .Values.sbiAddresses.defaultGW }};
            open5gs-nrfd -c /open5gs/config-map/nrf.yaml; 
          volumeMounts:
            - name: {{ .Release.Name }}-nrf-config
              mountPath: /open5gs/config-map/nrf.yaml
              subPath: "nrf.yaml"
            - mountPath: "/tls"
              name: tls
          securityContext:
             capabilities:
               add:
               - NET_ADMIN            
      {{- if .Values.controlPlaneNodes}}
      nodeSelector: {{- .Values.controlPlaneNodes.nodeSelector | toYaml | nindent 8 }}
      {{- end }}      
      volumes:
        - name: {{ .Release.Name }}-nrf-config
          configMap:
            name: {{ .Release.Name }}-nrf-config
        - name: tls
          secret:
            secretName: mtls-vplmn-nrf-cert
