apiVersion: v1
kind: Service
metadata:
  name: nssf
  labels:
    epc-mode: nssf
spec:
  selector:
    epc-mode: nssf
  ports:
    - protocol: TCP
      port: 443 
      targetPort: 443  
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nssf-deployment  
  labels:
    epc-mode: nssf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: nssf
  template:
    metadata:
      annotations:
         k8s.v1.cni.cncf.io/networks: '[
                 { "name": "{{ .Release.Name }}-sbi-nad",
                    "interface": "sbi",
                   "ips": [ {{- cat .Values.sbiAddresses.nssf "/" .Values.sbiAddresses.NetworkMask | nospace | quote }} ] }                   
         ]'    
      labels:
        epc-mode: nssf
    spec:
      serviceAccountName: {{ .Release.Name }}-k8s-wait-for
      initContainers:     
      - name: wait-for-nrf
        image: "{{ .Values.k8swait.repository }}:{{ .Values.k8swait.tag }}"
        imagePullPolicy: {{ .Values.k8swait.pullPolicy }}
        args:
          - "pod"
          - "-lepc-mode=nrf"
      - name: wait-for-scp
        image: "{{ .Values.k8swait.repository }}:{{ .Values.k8swait.tag }}"
        imagePullPolicy: {{ .Values.k8swait.pullPolicy }}
        args:
          - "pod"
          - "-lepc-mode=scp"          
      containers:
        - name: nssf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
          - ip route add {{ .Values.roamingSBInetwork }} via {{ .Values.sbiAddresses.defaultGW }};
            open5gs-nssfd -c /open5gs/config-map/nssf.yaml; 
          volumeMounts:
          - name: {{ .Release.Name }}-nssf-config
            mountPath: /open5gs/config-map/nssf.yaml
            subPath: "nssf.yaml"
          - mountPath: "/tls"
            name: tls
          securityContext:
             capabilities:
               add:
               - NET_ADMIN              
      {{- if .Values.controlPlaneNodes}}
      nodeSelector: {{- .Values.controlPlaneNodes.nodeSelector | toYaml | nindent 8 }}
      {{- end }}      
      volumes:
        - name: {{ .Release.Name }}-nssf-config
          configMap:
            name: {{ .Release.Name }}-nssf-config           
        - name: tls
          secret:
            secretName: mtls-vplmn-nssf-cert