apiVersion: v1
kind: Service
metadata:
  name: sepp-sbi
  labels:
    epc-mode: sepp
spec:
  selector:
    epc-mode: sepp
  ports:
    - protocol: TCP
      port: 443 
      targetPort: 443  
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sepp-deployment 
  labels:
    epc-mode: sepp
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: sepp
  template:
    metadata:
      annotations:
         linkerd.io/inject: disabled
         k8s.v1.cni.cncf.io/networks: >-
          [
            { "name": "{{ .Release.Name }}-sepp-control-nad" },
            { "name": "{{ .Release.Name }}-sepp-forward-nad" },
            { "name": "{{ .Release.Name }}-sbi-nad",
                    "interface": "sbi",
                   "ips": [ {{- cat .Values.sbiAddresses.sepp "/" .Values.sbiAddresses.NetworkMask | nospace | quote }} ] }
          ]    
      labels:
        epc-mode: sepp
    spec:
      serviceAccountName: {{ .Release.Name }}-k8s-wait-for                
      initContainers:
      - name: wait-for-nrf
        image: "{{ .Values.k8swait.repository }}:{{ .Values.k8swait.tag }}"
        imagePullPolicy: {{ .Values.k8swait.pullPolicy }}
        args:
          - "pod"
          - "-lepc-mode=nrf"      
      - name: wait-for-scp
        image: "{{ .Values.k8swait.repository }}:{{ .Values.k8swait.tag }}"
        imagePullPolicy: {{ .Values.k8swait.pullPolicy }}
        args:
          - "pod"
          - "-lepc-mode=scp"            
      containers:
      - name: sepp
        image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
        imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
        command: ["/bin/sh", "-c"]
        args:
        - ip route add {{ .Values.roamingSBInetwork }} via {{ .Values.sbiAddresses.defaultGW }};
          ip route add {{ .Values.sepp.control.roamingSEPP2ControlIP }} via {{ .Values.sepp.control.defaultGW }};
          ip route add {{ .Values.sepp.forward.roamingSEPP2forwardIP }} via {{ .Values.sepp.forward.defaultGW }};
          open5gs-seppd -c /open5gs/config-map/sepp.yaml; 
        volumeMounts:
        - name: {{ .Release.Name }}-sepp-config
          mountPath: /open5gs/config-map/sepp.yaml
          subPath: "sepp.yaml"           
        - mountPath: "/tls-sbi"
          name: tls-sbi
        - mountPath: "/tls-ext"
          name: tls-ext
        securityContext:
           capabilities:
             add:
             - NET_ADMIN
      volumes:
        - name: {{ .Release.Name }}-sepp-config
          configMap:
            name: {{ .Release.Name }}-sepp-config           
        - name: tls-sbi
          secret:
            secretName: mtls-vplmn-sepp-sbi-cert
        - name: tls-ext
          secret:
            secretName: mtls-vplmn-sepp-ext-cert