apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-bsf-config
  labels:
    epc-mode: bsf
data:
  bsf.yaml: |
    global:
      max:
        ue: 1024  
    logger:
        file:
          path: /var/log/open5gs/bsf.log
    bsf:
      default:
        tls:
          server:
            scheme: https
            private_key: /tls/tls.key
            cert: /tls/tls.crt
            verify_client: true
            verify_client_cacert: /tls/ca.crt
          client:
            scheme: https
            cacert: /tls/ca.crt
            client_private_key: /tls/tls.key
            client_cert: /tls/tls.crt
      sbi:
        server:
        - dev: sbi
          advertise: bsf.5gc.mnc{{ .Values.localPLMN.mnc }}.mcc{{ .Values.localPLMN.mcc }}.3gppnetwork.org
        client:
          scp:
          - uri: https://scp.5gc.mnc{{ .Values.localPLMN.mnc }}.mcc{{ .Values.localPLMN.mcc }}.3gppnetwork.org:7777        