apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nrf-config
  labels:
    epc-mode: nrf
data:
  nrf.yaml: |
    global:
      max:
        ue: 1024   
    logger:
        file:
          path: /var/log/open5gs/nrf.log
    nrf:
      default:
        tls:
          server:
            scheme: https
            private_key: /tls/tls.key
            cert: /tls/tls.crt
            verify_client: true
            verify_client_cacert: /tls/ca.crt
          client:
            scheme: https
            cacert: /tls/ca.crt
            client_private_key: /tls/tls.key
            client_cert: /tls/tls.crt
      serving:  # 5G roaming requires PLMN in NRF
        - plmn_id:
            mcc: {{ .Values.localPLMN.mcc }}
            mnc: {{ .Values.localPLMN.mnc }}
      sbi:
        server:
        - dev: sbi
          port: 7777
          advertise: nrf.5gc.mnc{{ .Values.localPLMN.mnc }}.mcc{{ .Values.localPLMN.mcc }}.3gppnetwork.org          