apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-scp-config
  labels:
    epc-mode: scp
data:
  scp.yaml: |
    global:
      max:
        ue: 1024  
    logger:
        file: /var/log/open5gs/scp.log
        #level: debug
    db_uri: mongodb://{{ .Release.Name }}-mongodb-svc/open5gs
    scp:
      default:
        tls:
          server:
            scheme: https
            private_key: /tls/tls.key
            cert: /tls/tls.crt
            verify_client: true
            verify_client_cacert: /tls/ca.crt
          client:
            scheme: https
            cacert: /tls/ca.crt
            client_private_key: /tls/tls.key
            client_cert: /tls/tls.crt
      sbi:
        server:
        - dev: sbi
          port: 7777
          advertise: scp.5gc.mnc{{ .Values.localPLMN.mnc }}.mcc{{ .Values.localPLMN.mcc }}.3gppnetwork.org
        client:
          nrf:
            - uri: https://nrf.5gc.mnc{{ .Values.localPLMN.mnc }}.mcc{{ .Values.localPLMN.mcc }}.3gppnetwork.org:7777