apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init-conf
data:
  init.conf: |
    lcp create int host-if int
    lcp create h-upf host-if h-upf
    lcp create v-upf host-if v-upf
    set interface mtu 9001 int
    set interface mtu 9001 h-upf
    set interface mtu 9001 v-upf
    set interface ip address int {{ .Values.config.intIPAddress }}/{{ .Values.config.intNetMask }}
    set interface ip address v-upf {{ .Values.config.vIPAddress }}/{{ .Values.config.vNetMask }}
    set interface ip address h-upf {{ .Values.config.hIPAddress }}/{{ .Values.config.hNetMask }}
    set interface state int up
    set interface state v-upf up
    set interface state h-upf up
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-startup-conf
data:
  startup.conf: |
      unix {
        nodaemon
        log /tmp/vpp.log
        full-coredump
        gid vpp
        interactive
        cli-listen /run/vpp/cli.sock
        exec /etc/vpp/init.conf
      }

      cpu {
        main-core CORE1
        corelist-workers CORE2
      }

      memory {
        main-heap-size 2G
      }
      api-trace {
        on
      }

      buffers {
        buffers-per-numa 128000
        default data-size 2048
        page-size default-hugepage
      }

      dpdk {
       dev {{ .Values.config.hinterfacePCI }} {name h-upf}
       dev {{ .Values.config.vinterfacePCI }} {name v-upf}
       dev {{ .Values.config.intInterfacePCI }} {name int}
      }

      api-segment {
        gid vpp
      }

      plugins {
        path /usr/lib/x86_64-linux-gnu/vpp_plugins/
        plugin dpdk_plugin.so { enable }
        plugin linux_cp_plugin.so { disable }
        plugin linux_nl_plugin.so { disable }
        plugin lcpng_if_plugin.so { enable }
        plugin lcpng_nl_plugin.so { enable }
      }

      lcpng {
        lcp-sync
        lcp-auto-subint
      } 

      logging {
        default-log-level info
        default-syslog-log-level crit
        class linux-cp/if { rate-limit 10000 level debug syslog-level debug }
        class linux-cp/nl { rate-limit 10000 level debug syslog-level debug }
      }