apiVersion: v1
kind: ConfigMap
metadata:
  name: vpp-entrypoint
data:
  entrypoint.sh: |
    #!/bin/bash
    set -e

    echo "[INFO] Copying config template..."
    cp -r /tmp/startup.conf /etc/vpp-startup.conf

    echo "[INFO] Detecting CPU layout..."
    cpu_list=$(grep Cpus_allowed_list /proc/self/status | awk '{print $2}')

    flat_cores=$(echo "$cpu_list" | sed 's/,/ /g' | xargs -n1 | while read range; do
      if echo "$range" | grep -q '-'; then
        seq $(echo $range | tr '-' ' ')
      else
        echo $range
      fi
    done)

    readarray -t cores_array <<EOF
    $(echo "$flat_cores")
    EOF

    mainCore=${cores_array[0]}
    workerCore=$(IFS=,; echo "${cores_array[*]:1}")

    echo "[INFO] Using mainCore=$mainCore and workerCore=$workerCore"
    sed -i "s/CORE1/$mainCore/g; s/CORE2/$workerCore/g" /etc/vpp-startup.conf

    echo "[INFO] Starting VPP..."